---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=.bandit.yaml
        files: ^eufy_security/.+\.py$
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        language_version: python3
        files: ^((eufy_security|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.json"
          - --quiet-level=2
        exclude_types: [json]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.0.1
        files: ^eufy_security/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml
        files: ^(eufy_security|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        files: ^eufy_security/.+\.py$
